import XCTest
@testable import stir

final class CopyTests: XCTestCase {

    // stir.md decision 22: every sound stir ships is generated by
    // tools/synthesize-sounds.py, so every case here must resolve to a file in
    // the bundle — a picker row that plays nothing is a silent alarm.
    func testEveryBundledSoundResolvesToAFile() {
        for sound in AlarmSound.allCases {
            XCTAssertNotNil(bundledSoundURL(sound.rawValue), "no file for alarm sound \(sound.rawValue)")
        }
        for sound in WhiteNoiseSound.allCases {
            XCTAssertNotNil(bundledSoundURL(sound.rawValue), "no file for sleep sound \(sound.rawValue)")
        }
    }

    // stir.md decision 30: every word stir shows is lowercase, except the names
    // of things that belong to somebody else.
    func testSoundNamesAreLowercase() {
        for name in AlarmSound.allCases.map(\.displayName) + WhiteNoiseSound.allCases.map(\.displayName) {
            XCTAssertEqual(name, name.lowercased(), "\(name) is capitalized")
        }
    }
}
